### ISSUE TITLE
Loading saved statuses from Firebase at startup is broken

### ISSUE THREAD

**Issue by RickvdStaaij** [CIMonitor/CIMonitor#132]
### What

Firebase saves arrays as objects. The objects should be parsed to an array again when load into the application. This currently doesn't happen when loading the saved statuses.

### Reproduction scenario

1. Use the Firebase config storage
1. Run the CIMonitor, and add some statuses (gitlab pipelines)
1. Restart the CIMonitor (now the Firebase config is load), and see that the data isn't parsed correctly

### Suggested fix

Make sure that the object to array parsing is done here:
https://github.com/CIMonitor/CIMonitor/blob/master/back-end/storage/Firebase.js#L23-L31

Instead of only here:
https://github.com/CIMonitor/CIMonitor/blob/master/back-end/config/loader/Firebase.js#L40-L51

The bug is caused by this section, due to not having the array parser:
https://github.com/CIMonitor/CIMonitor/blob/master/back-end/domain/status/persister/Firebase.js#L25-L32

**Comment by eXistenZNL** [comment]
Fixed in patch version 3.4.2
