### ISSUE TITLE
Status times are not saved in Firebase

### ISSUE THREAD

**Issue by RickvdStaaij** [CIMonitor/CIMonitor#139]
### What

When the statuses are saved to Firebase, the javascript Date objects are not recognized as valid data type by Firebase, and are stripped from the database.

### Reproduction scenario

1. Configure CIMonitor to save to Firebase
1. Submit a status to CIMonitor
1. See that the status is added to Firebase
1. See that a timestamp for the status is missing

### Suggested fix

- When saving to Firebase, `Date` objects should be converted to timestamps (integers)
- When loading from Firebase, integers that are timestamps should be converted to `Date` objects

**Comment by eXistenZNL** [comment]
I would suggest using `moment().format()` that outputs something like `2019-07-26T21:13:30+02:00` into the database. This makes it easier detectable, multi timezone proof, and converting back can be done easily with MomentJS too.

**Comment by RickvdStaaij** [comment]
Will be released/fixed in version `3.5.0`
