### ISSUE TITLE
Being able to load CIMonitor into an iframe

### ISSUE THREAD

**Issue by syphernl** [CIMonitor/CIMonitor#158]
### What

I'd like to show CIMonitor on my Grafana instance using the AJAX plugin. This plugin supports GET/POST or simply iframe. This works fine for random sites, however when I include a CIMonitor URL (either the dashboard or just /webhook/gitlab as a test) no response is given.

I have tested in https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_iframe as well and it doesn't work there either so ISTM something is blocking it. From what i've seen there are no explicit headers restricting frames though.

### Why

To be able to embed CIMonitor in other dashboards.

**Comment by eXistenZNL** [comment]
Hi @syphernl,

it seems to be working just fine: https://www.w3schools.com/code/tryit.asp?filename=GBUXUDUZ7AOH

Do you perhaps try to iframe a CIMonitor served via HTTP in a HTTPS Grafana? This is prevented by all modern browsers because of security issues (mixed content).

**Comment by RickvdStaaij** [comment]
Works here too:
![image](https://user-images.githubusercontent.com/6495166/74424614-91e1ca80-4e52-11ea-8e61-82421a711356.png)

**Comment by syphernl** [comment]
> Do you perhaps try to iframe a CIMonitor served via HTTP in a HTTPS Grafana? This is prevented by all modern browsers because of security issues (mixed content).

Ahhh yeah, I tried both my custom hostname (with SSL) and CIMonitor direct but neither worked. But the latter is then indeed because of insecure content and the former is probably because it sends `x-frame-options: SAMEORIGIN` ;-)
