### ISSUE TITLE
User name/pseudo with profil picture

### ISSUE THREAD

**Issue by debug29** [CIMonitor/CIMonitor#181]
# What
Add possibility to show user name/pseudo with the image
## Why
Because in our team not all our developper have an associated profil pic and we have some bot.

**Comment by RickvdStaaij** [comment]
Hi @debug29, thank you for your feature request! I will check the webhook data and see what's possible, will get back to you soon.

**Comment by RickvdStaaij** [comment]
@debug29 for what I can see, the usernames for GitHub and GitLab webhooks are available, so we could show those in the statuses. What do you think of the following:

![image](https://user-images.githubusercontent.com/6495166/166056404-f84e09bb-e990-4dc7-a8c6-f36113cc5eb6.png)
*Example: My username with an account icon have been added*

Or would you rather see a username below the avatar? That might take excessive space though. What do you think?

**Comment by RickvdStaaij** [comment]
@debug29 this feature is now released in [version 4.6.0](https://github.com/CIMonitor/CIMonitor/releases/tag/4.6.0), I hope this is what you wanted :ok_hand:

**Comment by debug29** [comment]
Sorry for the late reply, this is exactly what i was asking for. Thanks a lot !
