### ISSUE TITLE
Configurable failed deploy timeouts

### ISSUE THREAD

**Issue by eXistenZNL** [CIMonitor/CIMonitor#32]
### What

It would be nice to have the failed build timeout configurable via the config.

We currently have to wait 30 minutes with a broken deploy that does not report back for CiMonitor to update the status from running to failed. Although this is a sane default, I feel that some people could set this way lower if their projects only take 30 seconds to deploy so failures would be shown much faster.

**Comment by RickvdStaaij** [comment]
No build time-out is present in v2, closing issue
