### ISSUE TITLE
Show warning when websocket connection broken

### ISSUE THREAD

**Issue by syphernl** [CIMonitor/CIMonitor#33]
It could occur that the node process goes down, but the frontend doesn't notice this and keeps the current messages on the screen and (obviously) has no new messages added. Starting the node process again results in fresh messages to be sent.

In case there is an issue with connecting to the websocket it should probably add a big (red) warning on the dashboard.

**Comment by RickvdStaaij** [comment]
@syphernl good suggesting, labeled as feature, will try to pick this up soon.

**Comment by RickvdStaaij** [comment]
@syphernl Fixed in https://github.com/CIMonitor/CIMonitor/pull/37
